pipeline:
  name: python-pipeline-sample-flask-app
  identifier: pythonpipelinesampleflaskapp
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pythonsamplespipelineconnector
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: build test and run stage
        identifier: build_and_run_stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: compile python code
                  identifier: compile_python_code
                  spec:
                    connectorRef: dockerhubpat
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: python -m compileall ./
              - step:
                  type: Run
                  name: create dockerfile
                  identifier: create_dockerfile
                  spec:
                    connectorRef: dockerhubpat
                    image: alpine
                    shell: Sh
                    command: |-
                      touch pythondockerfile
                      cat > pythondockerfile <<- EOM
                      FROM python:3.10.6-alpine
                      WORKDIR /python-pipeline-samples
                      ADD . /python-pipeline-samples
                      RUN pip install -r requirements.txt
                      CMD ["python" , "app.py"]
                      EOM
                      cat pythondockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: build and push image to Dockerhub
                  identifier: build_and_push_image_to_Dockerhub
                  spec:
                    connectorRef: dockerhubpat
                    repo: victorialloyd/harness-python-flask-demo-app
                    tags:
                      - latest
                    dockerfile: pythondockerfile
